### PR TITLE
Feature/xpath separator (fixes #93)

### LINKED ISSUE #93: Separator for XML-Elements
readtext should give the user a way to separate XML-Elements in the generated Output.

Example:

library(readtext)
txt <- readtext("tvsubtitles.xml", text = "//tt:body")

Input Data:
  <tt:body>
    <tt:div style="defaultStyle">
      <tt:p xml:id="sub0" style="textCenter" region="bottom" begin="00:00:00.000" end="00:00:03.320">
        <tt:span style="textCyan">Wir haben exklusive Neuigkeiten</tt:span>
        <tt:br />
        <tt:span style="textCyan">im Fall Anis Amri.</tt:span>
      </tt:p>
      <tt:p xml:id="sub1" style="textCenter" region="bottom" begin="00:00:03.320" end="00:00:06.840">
        <tt:span style="textCyan">Die lassen Zweifel zu,</tt:span>
        <tt:br />
        <tt:span style="textCyan">ob das, was der Innenminister</tt:span>
      </tt:p>
      <tt:p xml:id="sub2" style="textCenter" region="bottom" begin="00:00:06.840" end="00:00:10.000">
        <tt:span style="textCyan">uns bisher dazu gesagt hat,</tt:span>
        <tt:br />
        <tt:span style="textCyan">tatsächlich stimmt.</tt:span>
      </tt:p>
      <tt:p xml:id="sub3" style="textCenter" region="bottom" begin="00:00:10.000" end="00:00:13.240">
        <tt:span style="textYellow">Ich habe den Eindruck aus NRW,</tt:span>
        <tt:br />
        <tt:span style="textYellow">dass alle Sicherheitsbehörden,</tt:span>
      </tt:p>
      <tt:p xml:id="sub4" style="textCenter" region="bottom" begin="00:00:13.240" end="00:00:15.880">
        <tt:span style="textYellow">auch die, die im Gemeinsamen</tt:span>
        <tt:br />
        <tt:span style="textYellow">Terrorabwehrzentrum</tt:span>
      </tt:p>
      <tt:p xml:id="sub5" style="textCenter" region="bottom" begin="00:00:15.880" end="00:00:19.240">
        <tt:span style="textYellow">zusammengearbeitet haben,</tt:span>
        <tt:br />
        <tt:span style="textYellow">alles an rechtlichen Möglichkeiten</tt:span>
      </tt:p>
      <tt:p xml:id="sub6" style="textCenter" region="bottom" begin="00:00:19.240" end="00:00:21.760">
        <tt:span style="textYellow">ausgeschöpft haben,</tt:span>
        <tt:br />
        <tt:span style="textYellow">um Anis Amri zu beobachten,</tt:span>
      </tt:p>
      <tt:p xml:id="sub7" style="textCenter" region="bottom" begin="00:00:21.760" end="00:00:24.280">
        <tt:span style="textYellow">abzuhören und</tt:span>
        <tt:br />
        <tt:span style="textYellow">möglicherweise in Haft zu bringen.</tt:span>
      </tt:p>
      <tt:p xml:id="sub8" style="textCenter" region="bottom" begin="00:00:30.440" end="00:00:33.280">
        <tt:span style="textCyan">Alle rechtlichen Möglichkeiten</tt:span>
        <tt:br />
        <tt:span style="textCyan">ausgeschöpft? Wirklich?</tt:span>
      </tt:p>
      <tt:p xml:id="sub9" style="textCenter" region="bottom" begin="00:00:33.320" end="00:00:37.840">
        <tt:span style="textCyan">Im Fall Anis Amri gibt es</tt:span>
        <tt:br />
        <tt:span style="textCyan">inzwischen täglich neue Details.</tt:span>
      </tt:p>
      <tt:p xml:id="sub10" style="textCenter" region="bottom" begin="00:00:37.880" end="00:00:40.760">
        <tt:span style="textCyan">Und immer mehr Zweifel,</tt:span>
        <tt:br />
        <tt:span style="textCyan">ob die Behörden alles getan haben,</tt:span>
      </tt:p>
      <tt:p xml:id="sub11" style="textCenter" region="bottom" begin="00:00:40.800" end="00:00:43.400">
        <tt:span style="textCyan">was in ihrer Macht stand,</tt:span>
        <tt:br />
        <tt:span style="textCyan">um Anis Amri aufzuhalten</tt:span>
      </tt:p>
      <tt:p xml:id="sub12" style="textCenter" region="bottom" begin="00:00:43.440" end="00:00:47.000">
        <tt:span style="textCyan">und das Attentat auf den Berliner</tt:span>
        <tt:br />
        <tt:span style="textCyan">Weihnachts-Markt zu verhindern.</tt:span>
      </tt:p>
      <tt:p xml:id="sub13" style="textCenter" region="bottom" begin="00:00:47.040" end="00:00:49.880">
        <tt:span style="textCyan">Immer größer wird der Druck</tt:span>
        <tt:br />
        <tt:span style="textCyan">auf NRW-Innenminister Jäger.</tt:span>
      </tt:p>
      <tt:p xml:id="sub14" style="textCenter" region="bottom" begin="00:00:49.880" end="00:00:53.640">
        <tt:span style="textCyan">Recherchen zeigen: Behörden in NRW</tt:span>
        <tt:br />
        <tt:span style="textCyan">haben entscheidende Chancen vertan,</tt:span>
      </tt:p>
      <tt:p xml:id="sub15" style="textCenter" region="bottom" begin="00:00:53.640" end="00:00:54.680">
        <tt:span style="textCyan">Anis Amri zu stoppen.</tt:span>
      </tt:p>
      <tt:p xml:id="sub16" style="textCenter" region="bottom" begin="00:00:55.480" end="00:00:56.600">
        <tt:span style="textWhite">Sie hatten ihn schon.</tt:span>
      </tt:p>
      <tt:p xml:id="sub17" style="textCenter" region="bottom" begin="00:00:56.640" end="00:00:57.760">
        <tt:span style="textWhite">Hier in Ravensburg</tt:span>
      </tt:p>
      <tt:p xml:id="sub18" style="textCenter" region="bottom" begin="00:00:57.840" end="00:01:01.000">
        <tt:span style="textWhite">kommt Anis Amri am Samstag,</tt:span>
        <tt:br />
        <tt:span style="textWhite">den 30.06.2016 ins Gefängnis.</tt:span>
      </tt:p>
      <tt:p xml:id="sub19" style="textCenter" region="bottom" begin="00:01:01.080" end="00:01:04.440">
        <tt:span style="textWhite">Polizisten greifen ihn zuvor</tt:span>
        <tt:br />

Result txt$text (Problems with bold markup):

"Wir haben exklusive Neuigkeitenim Fall Anis Amr**i.D**ie lassen Zweifel z**u,o**b das, was der Innenministe**ru**ns bisher dazu gesagt ha**t,t**atsächlich stimm**t.I**ch habe den Eindruck aus NR**W,d**ass alle Sicherheitsbehörde**n,a**uch die, die im Gemeinsame**nT**errorabwehrzentru**mz**usammengearbeitet habe**n,a**lles an rechtlichen Möglichkeite**na**usgeschöpft habe**n,u**m Anis Amri zu beobachte**n,a**bzuhören un**dm**öglicherweise in Haft zu bringe**n.A**lle rechtlichen Möglichkeitenausgeschöpft? Wirklic**h?**Im Fall Anis Amri gibt e**si**nzwischen täglich neue Detail**s.U**nd immer mehr Zweife**l,o**b die Behörden alles getan habe**n,w**as in ihrer Macht stan**d,u**m Anis Amri aufzuhalte**nu**nd das Attentat auf den Berline**rW**eihnachts-Markt zu verhinder**n.I**mmer größer wird der Druckauf NRW-Innenminister Jäge**r.R**echerchen zeigen: Behörden in NR**Wh**aben entscheidende Chancen verta**n,A**nis Amri zu stoppe**n.S**ie hatten ihn scho**n.H**ier in Ravensbur**gk**ommt Anis Amri am Samsta**g,d**en 30.06.2016 ins Gefängni**s.P**olizisten greifen ihn zuvo**ri**n einem Fernbus nach Zürich au**f.A**mri hat ... <truncated>

Typical Problem:

dass alle Sicherheitsbehörden,auch die, die im GemeinsamenTerrorabwehrzentrumzusammengearbeitet haben

### PR DESCRIPTION
**Pull request by adamobeng**

### CODE REVIEW

**Comment by adamobeng** [comment]
Good question. Didn't change any user-visible function signatures, so maybe just in a vignette?

**Comment by kbenoit** [comment]
It implies we should document the get functions, and describe the additional functions that can be passed through `...`. I can do that.

**Comment by adamobeng** [comment]
OK, that would be great. In case this would make for a better design, is there a sensible way to pass `...` to more than one function so they only consume what they want?

**Comment by kbenoit** [comment]
It will work the way you've done it here, where `get_xml()` will recognise the `collapse` argument separately from the other ellipsis arguments, but it's all unnamed ellipsis in the calling function `readtext()`. For now I'll add this documentation just to `readtext()`.

**Pull request merged**
